-- Run this script in Supabase: SQL Editor > New query > Run.
create table if not exists scholarship_programs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  minimum_gpa numeric(3,2) not null,
  is_active boolean not null default true
);
create table if not exists scholars (
  student_no text primary key,
  full_name text not null,
  course text not null,
  program_id bigint not null references scholarship_programs(id),
  status text not null default 'Active',
  created_at timestamptz not null default now()
);
create table if not exists grade_submissions (
  id bigint generated by default as identity primary key,
  student_no text not null references scholars(student_no),
  academic_year text not null,
  semester text not null,
  gwa numeric(3,2) not null check (gwa between 1.00 and 5.00),
  document_name text,
  submission_status text not null default 'For Verification',
  submitted_at timestamptz not null default now(),
  verified_at timestamptz,
  unique(student_no, academic_year, semester)
);
insert into scholarship_programs (name, minimum_gpa) values
  ('University Merit Scholarship', 1.75),
  ('Government Educational Grant', 2.00),
  ('Private Foundation Scholarship', 2.25),
  ('Academic Excellence Grant', 1.50)
on conflict (name) do nothing;
